# Generated by Django 2.2 on 2022-10-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wooey', '0045_add_created_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptversion',
            name='script_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='wooeyfile',
            name='filepath',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wooeyjob',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('deleted', 'Deleted'), ('FAILURE', 'Failed'), ('error', 'Error'), ('running', 'Running'), ('submitted', 'Submitted')], default='submitted', max_length=255),
        ),
    ]
